export const GAME = {
  title: "OMNIPATH",
  subtitle: "Read the moment. Shape your fate.",
  version: 8,
  focusPerRound: 2,
  controlPerRound: 2, // Legacy persisted resource name.
  openingOmenCounts: [1, 2],
  decisionMs: 12_000,
  fateResolution: 120,
  masteryMax: 50,
  introMs: 800,
  reactionMs: 5000,
  phaseMs: {
    MATCH_INTRO: 600,
    INITIATIVE_ROLL: 900,
    ROUND_START: 450,
    TURN_START: 200,
    DICE_ROLL: 600,
    ACTION_DECLARED: 350,
    REACTION_DECLARED: 350,
    RESOLUTION: 400,
    TURN_END: 350,
    SECOND_TURN: 200,
    ROUND_END: 300,
  },
  rewards: { xp: 90, coins: 35, mastery: 40, season: 75 },
  season: {
    id: "first-light",
    name: "The First Light",
    label: "SEASON 01",
    endsAt: "2026-11-01T00:00:00Z",
    levels: 50,
    xpPerLevel: 150,
  },
} as const;
export const RANKS = [
  "Stone",
  "Bronze",
  "Silver",
  "Gold",
  "Platinum",
  "Diamond",
  "Mythic",
];
