import type { Legend } from "../engine/types";
export const LEGENDS: Legend[] = [
  {
    id: "basajaun",
    compatibleCardTags: ["legend:basajaun"],
    initiativeBonus: 0,
    class: "Guardian",
    allowedDiceSizes: [4, 6, 8, 10, 12, 20],
    passiveRule: { trigger: "firstGuard", amount: 1 },
    name: "Basajaun",
    region: "Basque Country · Pyrenees",
    archetype: "Guardian / Nature",
    subtitle: "The forest remembers.",
    lore: "An ancient keeper of the wild, gathering strength beneath the quiet canopy.",
    hp: 20,
    passive: "Your first Ward each round gains +1.",
    active: {
      timing: "REACTION",
      name: "Ancient Ward",
      text: "1–4: gain Ward equal to half the Omen, rounded up.",
      requirement: { count: 1, min: 1, max: 4 },
      effects: [{ type: "GUARD", scaling: "halfDieUp" }],
    },
    diceSlots: [12, 8, 6],
    tags: ["nature", "guardian"],
    color: "#9fb798",
    artIndex: 0,
    animationProfile: "bark",
    approaches: ["Endurance", "Counterattack", "Heavy strength"],
  },
  {
    id: "anansi",
    compatibleCardTags: ["legend:anansi"],
    initiativeBonus: 3,
    class: "Trickster",
    allowedDiceSizes: [4, 6, 8, 10, 12, 20],
    passiveRule: { trigger: "firstManipulation", amount: 2 },
    name: "Anansi",
    region: "West African folklore",
    archetype: "Trickster / Prediction",
    subtitle: "Every thread tells a story.",
    lore: "A storyteller who finds a path through promises, secrets and possibilities.",
    hp: 18,
    passive: "Your first manipulation each round grants 2 Ward.",
    active: {
      timing: "REACTION",
      name: "Web Shift",
      text: "SWAP: redirect the enemy action back to its user.",
      requirement: { count: 1, symbol: "swap" },
      effects: [{ type: "REDIRECT" }],
    },
    diceSlots: [8, 8, 8],
    tags: ["trickster", "web"],
    color: "#c4a36f",
    artIndex: 1,
    animationProfile: "web",
    approaches: ["Assignment tricks", "Prediction", "Tempo disruption"],
  },
  {
    id: "tengu",
    compatibleCardTags: ["legend:tengu"],
    initiativeBonus: 4,
    class: "Duelist",
    allowedDiceSizes: [4, 6, 8, 10, 12, 20],
    passiveRule: { trigger: "preferred", amount: 1 },
    name: "Tengu",
    region: "Japan · Mountain folklore",
    archetype: "Precision / Counter",
    subtitle: "Stillness before the strike.",
    lore: "A watchful mountain warrior who reads the smallest shift in the wind.",
    hp: 18,
    passive: "Matching a card’s preferred value adds 1 damage.",
    active: {
      timing: "ACTION",
      name: "Wind Cut",
      text: "Exactly 5: deal 3 damage.",
      requirement: { count: 1, exact: 5, min: 5, max: 5 },
      effects: [{ type: "DAMAGE", amount: 3 }],
    },
    diceSlots: [10, 8, 6],
    tags: ["wind", "precision"],
    color: "#d49182",
    artIndex: 2,
    animationProfile: "wind",
    approaches: ["Precision attacks", "Counter stance", "Speed"],
  },
  {
    id: "leshy",
    compatibleCardTags: ["legend:leshy"],
    initiativeBonus: 1,
    class: "Shapeshifter",
    allowedDiceSizes: [4, 6, 8, 10, 12, 20],
    passiveRule: { trigger: "adapt", amount: 1 },
    name: "Leshy",
    region: "Slavic folklore",
    archetype: "Adaptive / Transform",
    subtitle: "Nothing stays as it seems.",
    lore: "A shifting presence at the edge of the path, wearing the shapes of the forest.",
    hp: 21,
    passive: "Once per round, a number requirement may miss by 1.",
    active: {
      timing: "ACTION",
      name: "Change Shape",
      text: "Gain 2 Ward and heal 1 Life.",
      requirement: { count: 1, min: 3, max: 6 },
      effects: [
        { type: "GUARD", amount: 2 },
        { type: "HEAL", amount: 1 },
      ],
    },
    diceSlots: [10, 8, 8],
    tags: ["nature", "transform"],
    color: "#83b3ad",
    artIndex: 3,
    animationProfile: "mist",
    approaches: ["Adaptation", "Transformation", "Forest Focus"],
  },
  {
    id: "quetzalcoatl",
    compatibleCardTags: ["legend:quetzalcoatl"],
    initiativeBonus: 2,
    class: "Mystic",
    allowedDiceSizes: [4, 6, 8, 10, 12, 20],
    passiveRule: { trigger: "categoryChange", amount: 1 },
    name: "Quetzalcoatl",
    region: "Mesoamerican traditions",
    archetype: "Momentum / Chain",
    subtitle: "Rise with the first light.",
    lore: "A feathered presence between earth and sky, carrying the promise of renewal.",
    hp: 19,
    passive: "Changing action category within a round adds 1 damage.",
    active: {
      timing: "ACTION",
      name: "Sky Offering",
      text: "Spend 1 Life. Store +2 damage for next round.",
      requirement: { count: 1, min: 2 },
      effects: [
        {
          type: "CONVERT",
          from: "hp",
          amount: 1,
          effects: [
            { type: "STATUS", status: "power", amount: 2, duration: 1 },
          ],
        },
      ],
    },
    diceSlots: [12, 10, 6],
    tags: ["celestial", "chain"],
    color: "#71c5b3",
    artIndex: 4,
    animationProfile: "sun",
    approaches: ["Chaining", "Momentum", "Energy conversion"],
  },
  {
    id: "maui",
    compatibleCardTags: ["legend:maui"],
    initiativeBonus: 2,
    class: "Hero / Trickster",
    allowedDiceSizes: [4, 6, 8, 10, 12, 20],
    passiveRule: { trigger: "holdOne", amount: 2 },
    name: "Māui",
    region: "Polynesian traditions",
    archetype: "Gambit / Tempo",
    subtitle: "Make the impossible yield.",
    lore: "An audacious voyager whose cunning reshapes the limits of the possible.",
    hp: 20,
    passive: "End your turn holding exactly one Omen: gain 2 Ward.",
    active: {
      timing: "ACTION",
      name: "Turn the Tide",
      text: "Deal 2 damage. If behind in Life, heal 2.",
      requirement: { count: 1, min: 3 },
      effects: [
        { type: "DAMAGE", amount: 2 },
        {
          type: "CONDITIONAL",
          condition: "behind",
          effects: [{ type: "HEAL", amount: 2 }],
        },
      ],
    },
    diceSlots: [10, 10, 6],
    tags: ["ocean", "gambit"],
    color: "#d1a37c",
    artIndex: 5,
    animationProfile: "wave",
    approaches: ["Tempo stealing", "Calculated gambits", "Comeback turns"],
  },
];
export const legendById = Object.fromEntries(
  LEGENDS.map((l) => [l.id, l]),
) as Record<Legend["id"], Legend>;
