import type { Legend } from "../engine/types";
export const LEGENDS: Legend[] = [
  {
    id: "basajaun",
    name: "Basajaun",
    region: "Basque Country · Pyrenees",
    archetype: "Guardian / Nature",
    subtitle: "The forest remembers.",
    lore: "An ancient keeper of the wild, gathering strength beneath the quiet canopy.",
    hp: 20,
    passive: "Your first Guard each round gains +1.",
    active: {
      name: "Old Growth",
      text: "Gain 2 Guard. Store +1 damage for next round.",
      requirement: { count: 1, min: 4 },
      effects: [
        { type: "GUARD", amount: 2 },
        { type: "STATUS", status: "power", amount: 1, duration: 1 },
      ],
    },
    diceSlots: [12, 8, 6],
    tags: ["nature", "guardian"],
    color: "#9fb798",
    artIndex: 0,
    animationProfile: "bark",
    approaches: ["Endurance", "Counterattack", "Heavy strength"],
  },
  {
    id: "anansi",
    name: "Anansi",
    region: "West African folklore",
    archetype: "Trickster / Prediction",
    subtitle: "Every thread tells a story.",
    lore: "A storyteller who finds a path through promises, secrets and possibilities.",
    hp: 18,
    passive: "Your first manipulation each round grants 2 Guard.",
    active: {
      name: "Loose Thread",
      text: "Disrupt the first enemy card: reduce its damage by 2.",
      requirement: { count: 1, min: 3 },
      effects: [{ type: "BLOCK_EFFECT", amount: 2 }],
    },
    diceSlots: [8, 8, 8],
    tags: ["trickster", "web"],
    color: "#c4a36f",
    artIndex: 1,
    animationProfile: "web",
    approaches: ["Assignment tricks", "Prediction", "Tempo disruption"],
  },
  {
    id: "tengu",
    name: "Tengu",
    region: "Japan · Mountain folklore",
    archetype: "Precision / Counter",
    subtitle: "Stillness before the strike.",
    lore: "A watchful mountain warrior who reads the smallest shift in the wind.",
    hp: 18,
    passive: "Matching a card’s preferred value adds 1 damage.",
    active: {
      name: "Wind Stance",
      text: "Gain 2 Guard. If the enemy attacks, deal 2 damage.",
      requirement: { count: 1, min: 3 },
      effects: [
        { type: "GUARD", amount: 2 },
        {
          type: "CONDITIONAL",
          condition: "enemyAttacking",
          effects: [{ type: "DAMAGE", amount: 2 }],
        },
      ],
    },
    diceSlots: [10, 8, 6],
    tags: ["wind", "precision"],
    color: "#d49182",
    artIndex: 2,
    animationProfile: "wind",
    approaches: ["Precision attacks", "Counter stance", "Speed"],
  },
  {
    id: "leshy",
    name: "Leshy",
    region: "Slavic folklore",
    archetype: "Adaptive / Transform",
    subtitle: "Nothing stays as it seems.",
    lore: "A shifting presence at the edge of the path, wearing the shapes of the forest.",
    hp: 21,
    passive: "Once per round, a number requirement may miss by 1.",
    active: {
      name: "Change Shape",
      text: "Gain 2 Guard and heal 1 HP.",
      requirement: { count: 1, min: 3, max: 6 },
      effects: [
        { type: "GUARD", amount: 2 },
        { type: "HEAL", amount: 1 },
      ],
    },
    diceSlots: [10, 8, 8],
    tags: ["nature", "transform"],
    color: "#83b3ad",
    artIndex: 3,
    animationProfile: "mist",
    approaches: ["Adaptation", "Transformation", "Forest control"],
  },
  {
    id: "quetzalcoatl",
    name: "Quetzalcoatl",
    region: "Mesoamerican traditions",
    archetype: "Momentum / Chain",
    subtitle: "Rise with the first light.",
    lore: "A feathered presence between earth and sky, carrying the promise of renewal.",
    hp: 19,
    passive: "Changing action category within a round adds 1 damage.",
    active: {
      name: "Sky Offering",
      text: "Spend 1 HP. Store +2 damage for next round.",
      requirement: { count: 1, min: 2 },
      effects: [
        {
          type: "CONVERT",
          from: "hp",
          amount: 1,
          effects: [
            { type: "STATUS", status: "power", amount: 2, duration: 1 },
          ],
        },
      ],
    },
    diceSlots: [12, 10, 6],
    tags: ["celestial", "chain"],
    color: "#71c5b3",
    artIndex: 4,
    animationProfile: "sun",
    approaches: ["Chaining", "Momentum", "Energy conversion"],
  },
  {
    id: "maui",
    name: "Māui",
    region: "Polynesian traditions",
    archetype: "Gambit / Tempo",
    subtitle: "Make the impossible yield.",
    lore: "An audacious voyager whose cunning reshapes the limits of the possible.",
    hp: 20,
    passive: "Leaving exactly one die unused grants 2 Guard.",
    active: {
      name: "Turn the Tide",
      text: "Deal 2 damage. If behind in HP, heal 2.",
      requirement: { count: 1, min: 3 },
      effects: [
        { type: "DAMAGE", amount: 2 },
        {
          type: "CONDITIONAL",
          condition: "behind",
          effects: [{ type: "HEAL", amount: 2 }],
        },
      ],
    },
    diceSlots: [10, 10, 6],
    tags: ["ocean", "gambit"],
    color: "#d1a37c",
    artIndex: 5,
    animationProfile: "wave",
    approaches: ["Tempo stealing", "Calculated gambits", "Comeback turns"],
  },
];
export const legendById = Object.fromEntries(
  LEGENDS.map((l) => [l.id, l]),
) as Record<Legend["id"], Legend>;
