import type { Legend } from "../engine/types";
export const LEGENDS: Legend[] = [
  {
    id: "basajaun",
    affinities: ["wild", "might", "spirit"],
    initiativeBonus: 0,
    class: "Guardian",
    allowedDiceSizes: [4, 6, 8, 10, 12, 20],
    passiveRule: {
      trigger: "firstGuard",
      amount: 1,
    },
    name: "Basajaun",
    region: "Basque Country · Pyrenees",
    archetype: "Guardian / Nature",
    subtitle: "The forest remembers.",
    lore: "An ancient keeper of the wild, gathering strength beneath the quiet canopy.",
    hp: 14,
    passive: "Your first Ward each round gains +1.",
    active: {
      category: "Ward",
      timing: "REACTION",
      name: "Ancient Ward",
      text: "Value 1–4: gain 1 Ward.",
      requirement: {
        count: 1,
        min: 1,
        max: 4,
      },
      effects: [
        {
          type: "GUARD",
          amount: 1,
        },
      ],
    },
    diceSlots: [12, 8, 6],
    tags: ["nature", "guardian"],
    color: "#9fb798",
    artIndex: 0,
    animationProfile: "bark",
    approaches: [
      "Build Ward",
      "Prepare a counterattack",
      "Spend protection for pressure",
    ],
  },
  {
    id: "anansi",
    affinities: ["guile", "wisdom", "chaos"],
    initiativeBonus: 3,
    class: "Trickster",
    allowedDiceSizes: [4, 6, 8, 10, 12, 20],
    passiveRule: {
      trigger: "firstManipulation",
      amount: 1,
    },
    name: "Anansi",
    region: "West African folklore",
    archetype: "Trickster / Prediction",
    subtitle: "Every thread tells a story.",
    lore: "A storyteller who finds a path through promises, secrets and possibilities.",
    hp: 14,
    passive: "Your first manipulation each round grants 1 Ward.",
    active: {
      category: "Manipulation",
      timing: "REACTION",
      name: "Web Shift",
      text: "SWAP: redirect the enemy action back to its user.",
      requirement: {
        count: 1,
        symbol: "swap",
      },
      effects: [
        {
          type: "REDIRECT",
        },
      ],
    },
    diceSlots: [8, 8, 8],
    tags: ["trickster", "web"],
    color: "#c4a36f",
    artIndex: 1,
    animationProfile: "web",
    approaches: ["Reveal information", "Disrupt Focus", "Bait a response"],
  },
  {
    id: "tengu",
    affinities: ["might", "wisdom", "order"],
    initiativeBonus: 4,
    class: "Duelist",
    allowedDiceSizes: [4, 6, 8, 10, 12, 20],
    passiveRule: {
      trigger: "preferred",
      amount: 1,
      value: 5,
    },
    name: "Tengu",
    region: "Japan · Mountain folklore",
    archetype: "Precision / Counter",
    subtitle: "Stillness before the strike.",
    lore: "A watchful mountain warrior who reads the smallest shift in the wind.",
    hp: 14,
    passive:
      "Spend a total Value of exactly 5: your damage ability deals +1 damage.",
    active: {
      category: "Attack",
      timing: "ACTION",
      name: "Wind Cut",
      text: "Exactly 5: deal 2 damage.",
      requirement: {
        count: 1,
        exact: 5,
        min: 5,
        max: 5,
      },
      effects: [
        {
          type: "DAMAGE",
          amount: 2,
        },
      ],
    },
    diceSlots: [10, 8, 6],
    tags: ["wind", "precision"],
    color: "#d49182",
    artIndex: 2,
    animationProfile: "wind",
    approaches: ["Refine a Value", "Precision attacks", "Hold a counter"],
  },
  {
    id: "leshy",
    affinities: ["wild", "chaos", "shadow"],
    initiativeBonus: 1,
    class: "Shapeshifter",
    allowedDiceSizes: [4, 6, 8, 10, 12, 20],
    passiveRule: {
      trigger: "adapt",
      amount: 1,
    },
    name: "Leshy",
    region: "Slavic folklore",
    archetype: "Adaptive / Transform",
    subtitle: "Nothing stays as it seems.",
    lore: "A shifting presence at the edge of the path, wearing the shapes of the forest.",
    hp: 13,
    passive: "Once per round, a number requirement may miss by 1.",
    active: {
      category: "Recovery",
      timing: "ACTION",
      name: "Change Shape",
      text: "Any Omen: gain 1 Focus and 1 Ward.",
      requirement: {
        count: 1,
        any: true,
      },
      effects: [
        {
          type: "GAIN_CONTROL",
          amount: 1,
        },
        {
          type: "GUARD",
          amount: 1,
        },
      ],
    },
    diceSlots: [10, 8, 8],
    tags: ["nature", "transform"],
    color: "#83b3ad",
    artIndex: 3,
    animationProfile: "mist",
    approaches: ["Convert Voids", "Modify Omens", "Apply steady pressure"],
  },
  {
    id: "quetzalcoatl",
    affinities: ["spirit", "might", "wisdom"],
    initiativeBonus: 2,
    class: "Mystic",
    allowedDiceSizes: [4, 6, 8, 10, 12, 20],
    passiveRule: {
      trigger: "categoryChange",
      amount: 1,
    },
    name: "Quetzalcoatl",
    region: "Mesoamerican traditions",
    archetype: "Momentum / Chain",
    subtitle: "Rise with the first light.",
    lore: "A feathered presence between earth and sky, carrying the promise of renewal.",
    hp: 14,
    passive: "Changing action category within a round adds 1 damage.",
    active: {
      category: "Setup",
      timing: "ACTION",
      name: "Sky Offering",
      text: "Any Omen: gain 1 Focus and empower your next damage effect by 1, until the end of your next turn.",
      requirement: {
        count: 1,
        any: true,
      },
      effects: [
        {
          type: "STATUS",
          status: "power",
          amount: 1,
          duration: 1,
        },
        {
          type: "GAIN_CONTROL",
          amount: 1,
        },
      ],
    },
    diceSlots: [12, 10, 6],
    tags: ["celestial", "chain"],
    color: "#71c5b3",
    artIndex: 4,
    animationProfile: "sun",
    approaches: ["Set up", "Change categories", "Finish a sequence"],
  },
  {
    id: "maui",
    affinities: ["guile", "might", "wild"],
    initiativeBonus: 2,
    class: "Hero / Trickster",
    allowedDiceSizes: [4, 6, 8, 10, 12, 20],
    passiveRule: {
      trigger: "holdOne",
      amount: 2,
    },
    name: "Māui",
    region: "Polynesian traditions",
    archetype: "Gambit / Tempo",
    subtitle: "Make the impossible yield.",
    lore: "An audacious voyager whose cunning reshapes the limits of the possible.",
    hp: 16,
    passive: "End your turn holding exactly one Omen: gain 2 Ward.",
    active: {
      category: "Attack",
      timing: "ACTION",
      name: "Turn the Tide",
      text: "Deal 1 damage. If another Omen is unused, gain 1 Focus.",
      requirement: {
        count: 1,
        min: 1,
      },
      effects: [
        {
          type: "DAMAGE",
          amount: 1,
        },
        {
          type: "CONDITIONAL",
          condition: "unusedDie",
          effects: [
            {
              type: "GAIN_CONTROL",
              amount: 1,
            },
          ],
        },
      ],
    },
    diceSlots: [10, 10, 6],
    tags: ["ocean", "gambit"],
    color: "#d1a37c",
    artIndex: 5,
    animationProfile: "wave",
    approaches: ["Pressure Ward", "Keep options open", "Hold one response"],
  },
];
export const legendById = Object.fromEntries(
  LEGENDS.map((l) => [l.id, l]),
) as Record<Legend["id"], Legend>;
