-- Mechanical v6: one shared Card pool. Historic catalog rows remain for foreign-key/replay history.
update public.content_catalog set starter=false;
update public.content_catalog set enabled=false where kind='die';
-- Shared pool v5: only the curated starter collection is granted to new accounts.
-- Shared pool v5: only the curated starter collection is granted to new accounts.
-- Shared pool v5: only the curated starter collection is granted to new accounts.
insert into public.content_catalog(id,kind,version,definition,starter) values
('basajaun','legend',6,'{"id":"basajaun","affinities":["wild","might","spirit"],"initiativeBonus":0,"class":"Guardian","allowedDiceSizes":[4,6,8,10,12,20],"passiveRule":{"trigger":"firstGuard","amount":1},"name":"Basajaun","region":"Basque Country · Pyrenees","archetype":"Guardian / Nature","subtitle":"The forest remembers.","lore":"An ancient keeper of the wild, gathering strength beneath the quiet canopy.","hp":21,"passive":"Your first Ward each round gains +1.","active":{"category":"Ward","timing":"REACTION","name":"Ancient Ward","text":"1–4: gain Ward equal to half the Omen, rounded up.","requirement":{"count":1,"min":1,"max":4},"effects":[{"type":"GUARD","scaling":"halfDieUp"}]},"diceSlots":[12,8,6],"tags":["nature","guardian"],"color":"#9fb798","artIndex":0,"animationProfile":"bark","approaches":["Endurance","Counterattack","Heavy strength"]}'::jsonb,true),
('anansi','legend',6,'{"id":"anansi","affinities":["guile","wisdom","chaos"],"initiativeBonus":3,"class":"Trickster","allowedDiceSizes":[4,6,8,10,12,20],"passiveRule":{"trigger":"firstManipulation","amount":2},"name":"Anansi","region":"West African folklore","archetype":"Trickster / Prediction","subtitle":"Every thread tells a story.","lore":"A storyteller who finds a path through promises, secrets and possibilities.","hp":18,"passive":"Your first manipulation each round grants 2 Ward.","active":{"category":"Manipulation","timing":"REACTION","name":"Web Shift","text":"SWAP: redirect the enemy action back to its user.","requirement":{"count":1,"symbol":"swap"},"effects":[{"type":"REDIRECT"}]},"diceSlots":[8,8,8],"tags":["trickster","web"],"color":"#c4a36f","artIndex":1,"animationProfile":"web","approaches":["Assignment tricks","Prediction","Tempo disruption"]}'::jsonb,true),
('tengu','legend',6,'{"id":"tengu","affinities":["might","wisdom","order"],"initiativeBonus":4,"class":"Duelist","allowedDiceSizes":[4,6,8,10,12,20],"passiveRule":{"trigger":"preferred","amount":1,"value":5},"name":"Tengu","region":"Japan · Mountain folklore","archetype":"Precision / Counter","subtitle":"Stillness before the strike.","lore":"A watchful mountain warrior who reads the smallest shift in the wind.","hp":20,"passive":"Spend a total Value of exactly 5: your damage ability deals +1 damage.","active":{"category":"Attack","timing":"ACTION","name":"Wind Cut","text":"Exactly 5: deal 3 damage.","requirement":{"count":1,"exact":5,"min":5,"max":5},"effects":[{"type":"DAMAGE","amount":3}]},"diceSlots":[10,8,6],"tags":["wind","precision"],"color":"#d49182","artIndex":2,"animationProfile":"wind","approaches":["Precision attacks","Counter stance","Speed"]}'::jsonb,false),
('leshy','legend',6,'{"id":"leshy","affinities":["wild","chaos","shadow"],"initiativeBonus":1,"class":"Shapeshifter","allowedDiceSizes":[4,6,8,10,12,20],"passiveRule":{"trigger":"adapt","amount":1},"name":"Leshy","region":"Slavic folklore","archetype":"Adaptive / Transform","subtitle":"Nothing stays as it seems.","lore":"A shifting presence at the edge of the path, wearing the shapes of the forest.","hp":20,"passive":"Once per round, a number requirement may miss by 1.","active":{"category":"Recovery","timing":"ACTION","name":"Change Shape","text":"Gain 2 Ward and heal 1 Life.","requirement":{"count":1,"min":3,"max":6},"effects":[{"type":"GUARD","amount":2},{"type":"HEAL","amount":1}]},"diceSlots":[10,8,8],"tags":["nature","transform"],"color":"#83b3ad","artIndex":3,"animationProfile":"mist","approaches":["Adaptation","Transformation","Forest Focus"]}'::jsonb,false),
('quetzalcoatl','legend',6,'{"id":"quetzalcoatl","affinities":["spirit","might","wisdom"],"initiativeBonus":2,"class":"Mystic","allowedDiceSizes":[4,6,8,10,12,20],"passiveRule":{"trigger":"categoryChange","amount":1},"name":"Quetzalcoatl","region":"Mesoamerican traditions","archetype":"Momentum / Chain","subtitle":"Rise with the first light.","lore":"A feathered presence between earth and sky, carrying the promise of renewal.","hp":20,"passive":"Changing action category within a round adds 1 damage.","active":{"category":"Setup","timing":"ACTION","name":"Sky Offering","text":"Spend 1 Life. Empower your next damage effect by 2. Expires at the end of your next turn.","requirement":{"count":1,"min":2,"life":1},"effects":[{"type":"STATUS","status":"power","amount":2,"duration":1}]},"diceSlots":[12,10,6],"tags":["celestial","chain"],"color":"#71c5b3","artIndex":4,"animationProfile":"sun","approaches":["Chaining","Momentum","Energy conversion"]}'::jsonb,false),
('maui','legend',6,'{"id":"maui","affinities":["guile","might","wild"],"initiativeBonus":2,"class":"Hero / Trickster","allowedDiceSizes":[4,6,8,10,12,20],"passiveRule":{"trigger":"holdOne","amount":2},"name":"Māui","region":"Polynesian traditions","archetype":"Gambit / Tempo","subtitle":"Make the impossible yield.","lore":"An audacious voyager whose cunning reshapes the limits of the possible.","hp":20,"passive":"End your turn holding exactly one Omen: gain 2 Ward.","active":{"category":"Attack","timing":"ACTION","name":"Turn the Tide","text":"Deal 2 damage. If behind in Life, heal 2.","requirement":{"count":1,"min":3},"effects":[{"type":"DAMAGE","amount":2},{"type":"CONDITIONAL","condition":"behind","effects":[{"type":"HEAL","amount":2}]}]},"diceSlots":[10,10,6],"tags":["ocean","gambit"],"color":"#d1a37c","artIndex":5,"animationProfile":"wave","approaches":["Tempo stealing","Calculated gambits","Comeback turns"]}'::jsonb,false),
('crush','card',6,'{"id":"crush","name":"Crush","category":"Attack","timing":"ACTION","requirement":{"count":1,"min":7},"text":"Deal 4 damage.","effects":[{"type":"DAMAGE","amount":4}],"priority":40,"archetype":"Attack","artIndex":0,"tags":["attack","action"],"mechanicalVersion":6,"rarity":"common","affinityRequirements":{"affinity":"might"},"set":"first-light","collectorNumber":1,"balanceMetadata":{"intent":"Attack option; overlapping Affinity access","complexity":1,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 7+"}'::jsonb,true),
('root-ward','card',6,'{"id":"root-ward","name":"Root Ward","category":"Ward","timing":"REACTION","requirement":{"count":1,"min":1,"max":3},"text":"Gain 3 Ward.","effects":[{"type":"GUARD","amount":3}],"priority":20,"archetype":"Ward","artIndex":0,"tags":["ward","reaction","low-value"],"mechanicalVersion":6,"rarity":"common","affinityRequirements":{"anyOf":[{"affinity":"wild"},{"affinity":"spirit"}]},"set":"first-light","collectorNumber":2,"balanceMetadata":{"intent":"Ward option; overlapping Affinity access","complexity":1,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 1–3"}'::jsonb,true),
('barkskin','card',6,'{"id":"barkskin","name":"Barkskin","category":"Counter","timing":"REACTION","requirement":{"count":1,"min":4,"max":6},"text":"Gain 3 Ward. If this attack then damages your Life, deal 2 damage back.","effects":[{"type":"GUARD","amount":3},{"type":"CONDITIONAL","condition":"enemyAttacking","effects":[{"type":"COUNTERSTRIKE","amount":2}]}],"priority":20,"archetype":"Counter","artIndex":0,"tags":["counter","reaction"],"mechanicalVersion":6,"rarity":"uncommon","affinityRequirements":{"anyOf":[{"affinity":"wild"},{"affinity":"order"}]},"set":"first-light","collectorNumber":3,"balanceMetadata":{"intent":"Counter option; overlapping Affinity access","complexity":2,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 4–6"}'::jsonb,true),
('herensuge','card',6,'{"id":"herensuge","name":"Herensuge","category":"Finisher","timing":"ACTION","requirement":{"count":2,"min":12},"text":"Deal 7 damage.","effects":[{"type":"DAMAGE","amount":7}],"priority":40,"archetype":"Finisher","artIndex":0,"tags":["finisher","action"],"mechanicalVersion":6,"rarity":"common","affinityRequirements":{"allOf":[{"affinity":"might"},{"affinity":"wild"}]},"set":"first-light","collectorNumber":4,"balanceMetadata":{"intent":"Finisher option; overlapping Affinity access","complexity":1,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"2 Values totaling 12+"}'::jsonb,true),
('deep-roots','card',6,'{"id":"deep-roots","name":"Deep Roots","category":"Recovery","timing":"ACTION","requirement":{"count":1,"min":2,"max":4},"text":"Heal 3 Life.","effects":[{"type":"HEAL","amount":3}],"priority":40,"archetype":"Recovery","artIndex":0,"tags":["recovery","action","low-value"],"mechanicalVersion":6,"rarity":"common","affinityRequirements":{"anyOf":[{"affinity":"wild"},{"affinity":"spirit"}]},"set":"first-light","collectorNumber":5,"balanceMetadata":{"intent":"Recovery option; overlapping Affinity access","complexity":1,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 2–4"}'::jsonb,true),
('oakheart','card',6,'{"id":"oakheart","name":"Oakheart","category":"Setup","timing":"ACTION","requirement":{"count":1,"min":4},"text":"Gain 2 Ward. Empower your next damage effect by 2. Expires at the end of your next turn.","effects":[{"type":"GUARD","amount":2},{"type":"STATUS","status":"power","amount":2,"duration":1}],"priority":40,"archetype":"Setup","artIndex":0,"tags":["setup","action"],"mechanicalVersion":6,"rarity":"uncommon","affinityRequirements":{"allOf":[{"affinity":"wild"},{"affinity":"might"}]},"set":"first-light","collectorNumber":6,"balanceMetadata":{"intent":"Setup option; overlapping Affinity access","complexity":2,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 4+"}'::jsonb,false),
('thorn-return','card',6,'{"id":"thorn-return","name":"Thorn Return","category":"Counter","timing":"REACTION","requirement":{"count":1,"min":3,"max":5,"condition":"enemyAttacking"},"text":"Against an attack: gain 2 Ward. If it then damages your Life, deal 3 damage back.","effects":[{"type":"CONDITIONAL","condition":"enemyAttacking","effects":[{"type":"GUARD","amount":2},{"type":"COUNTERSTRIKE","amount":3}]}],"priority":20,"archetype":"Counter","artIndex":0,"tags":["counter","reaction"],"mechanicalVersion":6,"rarity":"uncommon","affinityRequirements":{"anyOf":[{"affinity":"wild"},{"affinity":"shadow"}]},"set":"first-light","collectorNumber":7,"balanceMetadata":{"intent":"Counter option; overlapping Affinity access","complexity":2,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 3–5 · Against an attack"}'::jsonb,false),
('fell-the-axe','card',6,'{"id":"fell-the-axe","name":"Fell the Axe","category":"Attack","timing":"ACTION","requirement":{"count":1,"min":5},"text":"Deal 3 damage. If you have Ward, deal 1 more.","effects":[{"type":"DAMAGE","amount":3},{"type":"CONDITIONAL","condition":"guarding","effects":[{"type":"DAMAGE","amount":1}]}],"priority":40,"archetype":"Attack","artIndex":0,"tags":["attack","action"],"mechanicalVersion":6,"rarity":"common","affinityRequirements":{"anyOf":[{"affinity":"might"},{"affinity":"order"}]},"set":"first-light","collectorNumber":8,"balanceMetadata":{"intent":"Attack option; overlapping Affinity access","complexity":1,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 5+"}'::jsonb,false),
('sanctuary','card',6,'{"id":"sanctuary","name":"Sanctuary","category":"Ward","timing":"REACTION","requirement":{"count":1,"symbol":"guard"},"text":"Gain 6 Ward and cleanse all negative statuses.","effects":[{"type":"GUARD","amount":6},{"type":"CLEANSE"}],"priority":20,"archetype":"Ward","artIndex":0,"tags":["ward","reaction"],"mechanicalVersion":6,"rarity":"rare","affinityRequirements":{"affinity":"spirit"},"set":"first-light","collectorNumber":9,"balanceMetadata":{"intent":"Ward option; overlapping Affinity access","complexity":3,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Ward Sigil"}'::jsonb,false),
('silken-cut','card',6,'{"id":"silken-cut","name":"Silken Cut","category":"Attack","timing":"ACTION","requirement":{"count":1,"min":5},"text":"Deal 3 damage.","effects":[{"type":"DAMAGE","amount":3}],"priority":40,"archetype":"Attack","artIndex":1,"tags":["attack","action"],"mechanicalVersion":6,"rarity":"common","affinityRequirements":null,"set":"first-light","collectorNumber":10,"balanceMetadata":{"intent":"Attack option; universal access","complexity":1,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 5+"}'::jsonb,true),
('read-the-thread','card',6,'{"id":"read-the-thread","name":"Read the Thread","category":"Prediction","timing":"REACTION","requirement":{"count":1,"min":4},"text":"Deal 2 damage. If the enemy attacks, deal 2 more.","effects":[{"type":"DAMAGE","amount":2},{"type":"CONDITIONAL","condition":"enemyAttacking","effects":[{"type":"DAMAGE","amount":2}]}],"priority":20,"archetype":"Prediction","artIndex":1,"tags":["prediction","reaction"],"mechanicalVersion":6,"rarity":"uncommon","affinityRequirements":{"anyOf":[{"affinity":"guile"},{"affinity":"wisdom"}]},"set":"first-light","collectorNumber":11,"balanceMetadata":{"intent":"Prediction option; overlapping Affinity access","complexity":2,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 4+"}'::jsonb,true),
('web-shift','card',6,'{"id":"web-shift","name":"Web Shift","category":"Manipulation","timing":"REACTION","requirement":{"count":1,"symbol":"swap"},"text":"Redirect the declared enemy action back to its user.","effects":[{"type":"REDIRECT"}],"priority":20,"archetype":"Manipulation","artIndex":1,"tags":["manipulation","reaction"],"mechanicalVersion":6,"rarity":"uncommon","affinityRequirements":{"anyOf":[{"affinity":"guile"},{"affinity":"chaos"}]},"set":"first-light","collectorNumber":12,"balanceMetadata":{"intent":"Manipulation option; overlapping Affinity access","complexity":2,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Shift Sigil"}'::jsonb,true),
('false-promise','card',6,'{"id":"false-promise","name":"False Promise","category":"Prediction","timing":"ACTION","requirement":{"count":1,"min":3,"max":5},"text":"Deal 1 damage. If the enemy has Ward, deal 4 more.","effects":[{"type":"DAMAGE","amount":1},{"type":"CONDITIONAL","condition":"enemyGuarding","effects":[{"type":"DAMAGE","amount":4}]}],"priority":40,"archetype":"Prediction","artIndex":1,"tags":["prediction","action"],"mechanicalVersion":6,"rarity":"uncommon","affinityRequirements":{"affinity":"guile"},"set":"first-light","collectorNumber":13,"balanceMetadata":{"intent":"Prediction option; overlapping Affinity access","complexity":2,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 3–5"}'::jsonb,false),
('unravel','card',6,'{"id":"unravel","name":"Unravel","category":"Manipulation","timing":"REACTION","requirement":{"count":1,"exact":3,"min":3,"max":3,"control":1},"text":"Cancel this Action. Its Omens stay spent.","effects":[{"type":"CANCEL"}],"priority":20,"archetype":"Manipulation","artIndex":1,"tags":["manipulation","reaction","low-value"],"mechanicalVersion":6,"rarity":"uncommon","affinityRequirements":{"allOf":[{"affinity":"guile"},{"affinity":"wisdom"}]},"set":"first-light","collectorNumber":14,"balanceMetadata":{"intent":"Manipulation option; overlapping Affinity access","complexity":2,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value exactly 3 · 1 Focus"}'::jsonb,false),
('borrowed-time','card',6,'{"id":"borrowed-time","name":"Borrowed Time","category":"Setup","timing":"ACTION","requirement":{"count":1,"min":2,"max":4},"text":"Gain 2 Ward. Empower your next damage effect by 1. Expires at the end of your next turn.","effects":[{"type":"GUARD","amount":2},{"type":"STATUS","status":"power","amount":1,"duration":1}],"priority":40,"archetype":"Setup","artIndex":1,"tags":["setup","action","low-value"],"mechanicalVersion":6,"rarity":"uncommon","affinityRequirements":{"anyOf":[{"affinity":"guile"},{"affinity":"order"}]},"set":"first-light","collectorNumber":15,"balanceMetadata":{"intent":"Setup option; overlapping Affinity access","complexity":2,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 2–4"}'::jsonb,false),
('spider-s-patience','card',6,'{"id":"spider-s-patience","name":"Spider’s Patience","category":"Recovery","timing":"ACTION","requirement":{"count":1,"min":1,"max":2},"text":"Heal 3 Life.","effects":[{"type":"HEAL","amount":3}],"priority":40,"archetype":"Recovery","artIndex":1,"tags":["recovery","action","low-value"],"mechanicalVersion":6,"rarity":"common","affinityRequirements":{"anyOf":[{"affinity":"guile"},{"affinity":"shadow"}]},"set":"first-light","collectorNumber":16,"balanceMetadata":{"intent":"Recovery option; overlapping Affinity access","complexity":1,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 1–2"}'::jsonb,false),
('story-s-end','card',6,'{"id":"story-s-end","name":"Story’s End","category":"Finisher","timing":"ACTION","requirement":{"count":2,"min":11},"text":"Deal 6 damage. Deal 1 more if an enemy card is known.","effects":[{"type":"DAMAGE","amount":6},{"type":"CONDITIONAL","condition":"knownEnemy","effects":[{"type":"DAMAGE","amount":1}]}],"priority":40,"archetype":"Finisher","artIndex":1,"tags":["finisher","action"],"mechanicalVersion":6,"rarity":"rare","affinityRequirements":{"anyOf":[{"allOf":[{"affinity":"guile"},{"affinity":"might"}]},{"allOf":[{"affinity":"guile"},{"affinity":"wisdom"}]}]},"set":"first-light","collectorNumber":17,"balanceMetadata":{"intent":"Finisher option; overlapping Affinity access","complexity":3,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"2 Values totaling 11+"}'::jsonb,false),
('hidden-meaning','card',6,'{"id":"hidden-meaning","name":"Hidden Meaning","category":"Counter","timing":"REACTION","requirement":{"count":1,"any":true},"text":"Gain 1 Ward. If this attack then damages your Life, deal 1 damage back.","effects":[{"type":"GUARD","amount":1},{"type":"CONDITIONAL","condition":"enemyAttacking","effects":[{"type":"COUNTERSTRIKE","amount":1}]}],"priority":20,"archetype":"Counter","artIndex":1,"tags":["counter","reaction"],"mechanicalVersion":6,"rarity":"common","affinityRequirements":null,"set":"first-light","collectorNumber":18,"balanceMetadata":{"intent":"Counter option; universal access","complexity":1,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Any Omen face"}'::jsonb,true),
('gale-cut','card',6,'{"id":"gale-cut","name":"Gale Cut","category":"Attack","timing":"ACTION","requirement":{"count":1,"min":4,"max":6},"text":"Deal 3 damage.","effects":[{"type":"DAMAGE","amount":3}],"priority":40,"archetype":"Attack","artIndex":2,"tags":["attack","action"],"mechanicalVersion":6,"rarity":"common","affinityRequirements":{"anyOf":[{"affinity":"might"},{"affinity":"wisdom"}]},"set":"first-light","collectorNumber":19,"balanceMetadata":{"intent":"Attack option; overlapping Affinity access","complexity":1,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 4–6"}'::jsonb,false),
('perfect-riposte','card',6,'{"id":"perfect-riposte","name":"Perfect Riposte","category":"Counter","timing":"REACTION","requirement":{"count":1,"min":4,"max":6,"condition":"enemyAttacking"},"text":"Against an attack: gain 2 Ward and deal 2 damage before it resolves.","effects":[{"type":"GUARD","amount":2},{"type":"DAMAGE","amount":2}],"priority":20,"archetype":"Counter","artIndex":2,"tags":["counter","reaction"],"mechanicalVersion":6,"rarity":"uncommon","affinityRequirements":{"anyOf":[{"affinity":"wisdom"},{"affinity":"order"}]},"set":"first-light","collectorNumber":20,"balanceMetadata":{"intent":"Counter option; overlapping Affinity access","complexity":2,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 4–6 · Against an attack"}'::jsonb,false),
('sky-sever','card',6,'{"id":"sky-sever","name":"Sky Sever","category":"Finisher","timing":"ACTION","requirement":{"count":2,"min":11},"text":"Deal 6 damage.","effects":[{"type":"DAMAGE","amount":6}],"priority":40,"archetype":"Finisher","artIndex":2,"tags":["finisher","action"],"mechanicalVersion":6,"rarity":"mythic","affinityRequirements":{"allOf":[{"affinity":"might"},{"affinity":"wisdom"}]},"set":"first-light","collectorNumber":21,"balanceMetadata":{"intent":"Finisher option; overlapping Affinity access","complexity":4,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"2 Values totaling 11+"}'::jsonb,false),
('first-wind','card',6,'{"id":"first-wind","name":"First Wind","category":"Attack","timing":"ACTION","requirement":{"count":1,"min":2,"max":4},"text":"Deal 2 damage.","effects":[{"type":"DAMAGE","amount":2}],"priority":40,"archetype":"Attack","artIndex":2,"tags":["attack","action","low-value"],"mechanicalVersion":6,"rarity":"common","affinityRequirements":null,"set":"first-light","collectorNumber":22,"balanceMetadata":{"intent":"Attack option; universal access","complexity":1,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 2–4"}'::jsonb,false),
('still-mind','card',6,'{"id":"still-mind","name":"Still Mind","category":"Recovery","timing":"ACTION","requirement":{"count":1,"min":2,"max":3},"text":"Heal 2 Life and cleanse negative statuses.","effects":[{"type":"HEAL","amount":2},{"type":"CLEANSE"}],"priority":40,"archetype":"Recovery","artIndex":2,"tags":["recovery","action","low-value"],"mechanicalVersion":6,"rarity":"uncommon","affinityRequirements":{"anyOf":[{"affinity":"wisdom"},{"affinity":"spirit"}]},"set":"first-light","collectorNumber":23,"balanceMetadata":{"intent":"Recovery option; overlapping Affinity access","complexity":2,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 2–3"}'::jsonb,false),
('raven-wing','card',6,'{"id":"raven-wing","name":"Raven Wing","category":"Manipulation","timing":"REACTION","requirement":{"count":1,"symbol":"redirect","condition":"enemyAttacking"},"text":"Prevent up to 4 damage from this Action.","effects":[{"type":"BLOCK_EFFECT","amount":4}],"priority":20,"archetype":"Manipulation","artIndex":2,"tags":["manipulation","reaction"],"mechanicalVersion":6,"rarity":"rare","affinityRequirements":{"anyOf":[{"affinity":"guile"},{"affinity":"order"}]},"set":"first-light","collectorNumber":24,"balanceMetadata":{"intent":"Manipulation option; overlapping Affinity access","complexity":3,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Redirect Sigil · Against an attack"}'::jsonb,false),
('peak-strike','card',6,'{"id":"peak-strike","name":"Peak Strike","category":"Attack","timing":"ACTION","requirement":{"count":1,"min":7},"text":"Deal 4 damage.","effects":[{"type":"DAMAGE","amount":4}],"priority":40,"archetype":"Attack","artIndex":2,"tags":["attack","action"],"mechanicalVersion":6,"rarity":"common","affinityRequirements":{"allOf":[{"affinity":"might"},{"affinity":"wisdom"}]},"set":"first-light","collectorNumber":25,"balanceMetadata":{"intent":"Attack option; overlapping Affinity access","complexity":1,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 7+"}'::jsonb,false),
('windstep','card',6,'{"id":"windstep","name":"Windstep","category":"Setup","timing":"ACTION","requirement":{"count":1,"any":true},"text":"Gain 1 Ward. Empower your next damage effect by 1. Expires at the end of your next turn.","effects":[{"type":"GUARD","amount":1},{"type":"STATUS","status":"power","amount":1,"duration":1}],"priority":40,"archetype":"Setup","artIndex":2,"tags":["setup","action"],"mechanicalVersion":6,"rarity":"common","affinityRequirements":null,"set":"first-light","collectorNumber":26,"balanceMetadata":{"intent":"Setup option; universal access","complexity":1,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Any Omen face"}'::jsonb,false),
('watchful-blade','card',6,'{"id":"watchful-blade","name":"Watchful Blade","category":"Prediction","timing":"REACTION","requirement":{"count":1,"min":5,"max":7,"condition":"enemyAttacking"},"text":"Against an attack: deal 4 damage before it resolves.","effects":[{"type":"DAMAGE","amount":4}],"priority":20,"archetype":"Prediction","artIndex":2,"tags":["prediction","reaction"],"mechanicalVersion":6,"rarity":"rare","affinityRequirements":{"anyOf":[{"affinity":"wisdom"},{"affinity":"order"}]},"set":"first-light","collectorNumber":27,"balanceMetadata":{"intent":"Prediction option; overlapping Affinity access","complexity":3,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 5–7 · Against an attack"}'::jsonb,false),
('mountain-silence','card',6,'{"id":"mountain-silence","name":"Mountain Silence","category":"Ward","timing":"REACTION","requirement":{"count":1,"min":8},"text":"Gain 5 Ward.","effects":[{"type":"GUARD","amount":5}],"priority":20,"archetype":"Ward","artIndex":2,"tags":["ward","reaction"],"mechanicalVersion":6,"rarity":"common","affinityRequirements":{"anyOf":[{"affinity":"spirit"},{"affinity":"order"}]},"set":"first-light","collectorNumber":28,"balanceMetadata":{"intent":"Ward option; overlapping Affinity access","complexity":1,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 8+"}'::jsonb,false),
('falling-leaf','card',6,'{"id":"falling-leaf","name":"Falling Leaf","category":"Attack","timing":"ACTION","requirement":{"count":1,"min":1,"max":2},"text":"Deal 2 damage.","effects":[{"type":"DAMAGE","amount":2}],"priority":40,"archetype":"Attack","artIndex":2,"tags":["attack","action","low-value"],"mechanicalVersion":6,"rarity":"common","affinityRequirements":{"anyOf":[{"affinity":"wild"},{"affinity":"wisdom"}]},"set":"first-light","collectorNumber":29,"balanceMetadata":{"intent":"Attack option; overlapping Affinity access","complexity":1,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 1–2"}'::jsonb,false),
('branch-lash','card',6,'{"id":"branch-lash","name":"Branch Lash","category":"Attack","timing":"ACTION","requirement":{"count":1,"min":6,"max":8},"text":"Deal 4 damage.","effects":[{"type":"DAMAGE","amount":4}],"priority":40,"archetype":"Attack","artIndex":3,"tags":["attack","action"],"mechanicalVersion":6,"rarity":"common","affinityRequirements":{"affinity":"wild"},"set":"first-light","collectorNumber":30,"balanceMetadata":{"intent":"Attack option; overlapping Affinity access","complexity":1,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 6–8"}'::jsonb,false),
('moss-mantle','card',6,'{"id":"moss-mantle","name":"Moss Mantle","category":"Ward","timing":"REACTION","requirement":{"count":1,"min":1,"max":3},"text":"Gain 2 Ward and heal 1 Life.","effects":[{"type":"GUARD","amount":2},{"type":"HEAL","amount":1}],"priority":20,"archetype":"Ward","artIndex":3,"tags":["ward","reaction","low-value"],"mechanicalVersion":6,"rarity":"common","affinityRequirements":{"anyOf":[{"allOf":[{"affinity":"wild"},{"affinity":"spirit"}]},{"affinity":"shadow"}]},"set":"first-light","collectorNumber":31,"balanceMetadata":{"intent":"Ward option; overlapping Affinity access","complexity":1,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 1–3"}'::jsonb,true),
('wolf-shape','card',6,'{"id":"wolf-shape","name":"Wolf Shape","category":"Attack","timing":"ACTION","requirement":{"count":1,"min":7},"text":"Deal 3 damage. If you were behind in Life, deal 2 more.","effects":[{"type":"DAMAGE","amount":3},{"type":"CONDITIONAL","condition":"behind","effects":[{"type":"DAMAGE","amount":2}]}],"priority":40,"archetype":"Attack","artIndex":3,"tags":["attack","action"],"mechanicalVersion":6,"rarity":"common","affinityRequirements":{"anyOf":[{"affinity":"wild"},{"affinity":"shadow"}]},"set":"first-light","collectorNumber":32,"balanceMetadata":{"intent":"Attack option; overlapping Affinity access","complexity":1,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 7+"}'::jsonb,false),
('lost-path','card',6,'{"id":"lost-path","name":"Lost Path","category":"Manipulation","timing":"REACTION","requirement":{"count":1,"min":4,"max":6,"condition":"enemyAttacking"},"text":"Prevent up to 3 damage from this Action.","effects":[{"type":"BLOCK_EFFECT","amount":3}],"priority":20,"archetype":"Manipulation","artIndex":3,"tags":["manipulation","reaction"],"mechanicalVersion":6,"rarity":"uncommon","affinityRequirements":{"anyOf":[{"affinity":"chaos"},{"affinity":"order"}]},"set":"first-light","collectorNumber":33,"balanceMetadata":{"intent":"Manipulation option; overlapping Affinity access","complexity":2,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 4–6 · Against an attack"}'::jsonb,false),
('new-skin','card',6,'{"id":"new-skin","name":"New Skin","category":"Recovery","timing":"ACTION","requirement":{"count":1,"min":3,"max":5},"text":"Heal 3 Life and cleanse negative statuses.","effects":[{"type":"HEAL","amount":3},{"type":"CLEANSE"}],"priority":40,"archetype":"Recovery","artIndex":3,"tags":["recovery","action"],"mechanicalVersion":6,"rarity":"uncommon","affinityRequirements":{"anyOf":[{"affinity":"wild"},{"affinity":"chaos"}]},"set":"first-light","collectorNumber":34,"balanceMetadata":{"intent":"Recovery option; overlapping Affinity access","complexity":2,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 3–5"}'::jsonb,false),
('bramble-trap','card',6,'{"id":"bramble-trap","name":"Bramble Counter","category":"Counter","timing":"REACTION","requirement":{"count":1,"min":2,"max":4,"condition":"enemyAttacking"},"text":"Against an attack: gain 2 Ward. If this attack then damages your Life, deal 2 damage back.","effects":[{"type":"CONDITIONAL","condition":"enemyAttacking","effects":[{"type":"GUARD","amount":2},{"type":"COUNTERSTRIKE","amount":2}]}],"priority":20,"archetype":"Counter","artIndex":3,"tags":["counter","reaction","low-value"],"mechanicalVersion":6,"rarity":"uncommon","affinityRequirements":{"anyOf":[{"affinity":"wild"},{"affinity":"guile"}]},"set":"first-light","collectorNumber":35,"balanceMetadata":{"intent":"Counter option; overlapping Affinity access","complexity":2,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 2–4 · Against an attack"}'::jsonb,false),
('wild-bloom','card',6,'{"id":"wild-bloom","name":"Wild Bloom","category":"Recovery","timing":"ACTION","requirement":{"count":1,"symbol":"guard"},"text":"Heal 4 Life and gain 2 Ward.","effects":[{"type":"HEAL","amount":4},{"type":"GUARD","amount":2}],"priority":40,"archetype":"Recovery","artIndex":3,"tags":["recovery","action"],"mechanicalVersion":6,"rarity":"rare","affinityRequirements":{"anyOf":[{"affinity":"wild"},{"affinity":"spirit"}]},"set":"first-light","collectorNumber":36,"balanceMetadata":{"intent":"Recovery option; overlapping Affinity access","complexity":3,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Ward Sigil"}'::jsonb,false),
('crooked-bough','card',6,'{"id":"crooked-bough","name":"Crooked Bough","category":"Attack","timing":"ACTION","requirement":{"count":1,"min":3,"max":4},"text":"Deal 3 damage.","effects":[{"type":"DAMAGE","amount":3}],"priority":40,"archetype":"Attack","artIndex":3,"tags":["attack","action","low-value"],"mechanicalVersion":6,"rarity":"common","affinityRequirements":{"anyOf":[{"affinity":"wild"},{"affinity":"chaos"}]},"set":"first-light","collectorNumber":37,"balanceMetadata":{"intent":"Attack option; overlapping Affinity access","complexity":1,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 3–4"}'::jsonb,false),
('night-spores','card',6,'{"id":"night-spores","name":"Night Spores","category":"Setup","timing":"ACTION","requirement":{"count":1,"min":4,"max":6},"text":"Poison: at the start of the enemy’s next turn, they lose 2 Life once. Gain 1 Ward.","effects":[{"type":"STATUS","status":"poison","target":"enemy","amount":2,"duration":1},{"type":"GUARD","amount":1}],"priority":40,"archetype":"Setup","artIndex":3,"tags":["setup","action"],"mechanicalVersion":6,"rarity":"rare","affinityRequirements":{"anyOf":[{"affinity":"shadow"},{"affinity":"chaos"}]},"set":"first-light","collectorNumber":38,"balanceMetadata":{"intent":"Setup option; overlapping Affinity access","complexity":3,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 4–6"}'::jsonb,false),
('sun-lance','card',6,'{"id":"sun-lance","name":"Sun Lance","category":"Attack","timing":"ACTION","requirement":{"count":1,"min":6},"text":"Deal 4 damage.","effects":[{"type":"DAMAGE","amount":4}],"priority":40,"archetype":"Attack","artIndex":4,"tags":["attack","action"],"mechanicalVersion":6,"rarity":"common","affinityRequirements":{"anyOf":[{"affinity":"might"},{"affinity":"spirit"}]},"set":"first-light","collectorNumber":39,"balanceMetadata":{"intent":"Attack option; overlapping Affinity access","complexity":1,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 6+"}'::jsonb,true),
('first-light','card',6,'{"id":"first-light","name":"First Light","category":"Setup","timing":"ACTION","requirement":{"count":1,"min":2,"max":5},"text":"Heal 1 Life. Empower your next damage effect by 2. Expires at the end of your next turn.","effects":[{"type":"HEAL","amount":1},{"type":"STATUS","status":"power","amount":2,"duration":1}],"priority":40,"archetype":"Setup","artIndex":4,"tags":["setup","action"],"mechanicalVersion":6,"rarity":"common","affinityRequirements":{"anyOf":[{"affinity":"spirit"},{"affinity":"wisdom"}]},"set":"first-light","collectorNumber":40,"balanceMetadata":{"intent":"Setup option; overlapping Affinity access","complexity":1,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 2–5"}'::jsonb,false),
('offering','card',6,'{"id":"offering","name":"Offering","category":"Setup","timing":"ACTION","requirement":{"count":1,"any":true,"life":2},"text":"Spend 2 Life. Empower your next damage effect by 3. Expires at the end of your next turn.","effects":[{"type":"STATUS","status":"power","amount":3,"duration":1}],"priority":40,"archetype":"Setup","artIndex":4,"tags":["setup","action"],"mechanicalVersion":6,"rarity":"mythic","affinityRequirements":{"anyOf":[{"affinity":"shadow"},{"affinity":"spirit"}]},"set":"first-light","collectorNumber":41,"balanceMetadata":{"intent":"Setup option; overlapping Affinity access","complexity":4,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Any Omen face · 2 Life"}'::jsonb,false),
('dawn-shield','card',6,'{"id":"dawn-shield","name":"Dawn Shield","category":"Counter","timing":"REACTION","requirement":{"count":1,"min":4},"text":"Gain 2 Ward. If this attack then damages your Life, deal 1 damage back.","effects":[{"type":"GUARD","amount":2},{"type":"CONDITIONAL","condition":"enemyAttacking","effects":[{"type":"COUNTERSTRIKE","amount":1}]}],"priority":20,"archetype":"Counter","artIndex":4,"tags":["counter","reaction"],"mechanicalVersion":6,"rarity":"common","affinityRequirements":{"anyOf":[{"affinity":"spirit"},{"affinity":"order"}]},"set":"first-light","collectorNumber":42,"balanceMetadata":{"intent":"Counter option; overlapping Affinity access","complexity":1,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 4+"}'::jsonb,false),
('open-sky','card',6,'{"id":"open-sky","name":"Open Sky","category":"Manipulation","timing":"REACTION","requirement":{"count":1,"min":5,"max":7,"condition":"enemyAttacking"},"text":"Prevent up to 2 damage from this Action. Gain 1 Ward.","effects":[{"type":"BLOCK_EFFECT","amount":2},{"type":"GUARD","amount":1}],"priority":20,"archetype":"Manipulation","artIndex":4,"tags":["manipulation","reaction"],"mechanicalVersion":6,"rarity":"uncommon","affinityRequirements":{"anyOf":[{"affinity":"wisdom"},{"affinity":"order"}]},"set":"first-light","collectorNumber":43,"balanceMetadata":{"intent":"Manipulation option; overlapping Affinity access","complexity":2,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 5–7 · Against an attack"}'::jsonb,false),
('burning-crown','card',6,'{"id":"burning-crown","name":"Burning Crown","category":"Finisher","timing":"ACTION","requirement":{"count":1,"min":10,"life":2},"text":"Spend 2 Life to deal 7 damage.","effects":[{"type":"DAMAGE","amount":7}],"priority":40,"archetype":"Finisher","artIndex":4,"tags":["finisher","action"],"mechanicalVersion":6,"rarity":"mythic","affinityRequirements":{"anyOf":[{"allOf":[{"affinity":"might"},{"affinity":"spirit"}]},{"allOf":[{"affinity":"might"},{"affinity":"chaos"}]}]},"set":"first-light","collectorNumber":44,"balanceMetadata":{"intent":"Finisher option; overlapping Affinity access","complexity":4,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 10+ · 2 Life"}'::jsonb,false),
('horizon','card',6,'{"id":"horizon","name":"Horizon","category":"Prediction","timing":"ACTION","requirement":{"count":1,"min":5},"text":"Deal 2 damage. If this is your third ability or later this round, deal 2 more.","effects":[{"type":"DAMAGE","amount":2},{"type":"CONDITIONAL","condition":"threeActions","effects":[{"type":"DAMAGE","amount":2}]}],"priority":40,"archetype":"Prediction","artIndex":4,"tags":["prediction","action"],"mechanicalVersion":6,"rarity":"rare","affinityRequirements":{"anyOf":[{"allOf":[{"affinity":"might"},{"affinity":"wisdom"}]},{"affinity":"guile"}]},"set":"first-light","collectorNumber":45,"balanceMetadata":{"intent":"Prediction option; overlapping Affinity access","complexity":3,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 5+"}'::jsonb,false),
('daring-feint','card',6,'{"id":"daring-feint","name":"Daring Feint","category":"Attack","timing":"ACTION","requirement":{"count":1,"min":3,"max":5},"text":"Deal 2 damage. If another Omen is unused, deal 1 more.","effects":[{"type":"DAMAGE","amount":2},{"type":"CONDITIONAL","condition":"unusedDie","effects":[{"type":"DAMAGE","amount":1}]}],"priority":40,"archetype":"Attack","artIndex":5,"tags":["attack","action"],"mechanicalVersion":6,"rarity":"uncommon","affinityRequirements":{"anyOf":[{"affinity":"guile"},{"affinity":"might"}]},"set":"first-light","collectorNumber":46,"balanceMetadata":{"intent":"Attack option; overlapping Affinity access","complexity":2,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 3–5"}'::jsonb,true),
('turnabout','card',6,'{"id":"turnabout","name":"Turnabout","category":"Counter","timing":"REACTION","requirement":{"count":1,"min":3,"max":5},"text":"Gain 2 Ward. If you were behind in Life and this attack damages your Life, deal 3 damage back.","effects":[{"type":"GUARD","amount":2},{"type":"CONDITIONAL","condition":"behind","effects":[{"type":"COUNTERSTRIKE","amount":3}]}],"priority":20,"archetype":"Counter","artIndex":5,"tags":["counter","reaction"],"mechanicalVersion":6,"rarity":"uncommon","affinityRequirements":{"anyOf":[{"affinity":"guile"},{"affinity":"shadow"}]},"set":"first-light","collectorNumber":47,"balanceMetadata":{"intent":"Counter option; overlapping Affinity access","complexity":2,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 3–5"}'::jsonb,false),
('rising-tide','card',6,'{"id":"rising-tide","name":"Rising Tide","category":"Recovery","timing":"ACTION","requirement":{"count":1,"min":2,"max":4},"text":"Heal 2 Life. If you were behind in Life, heal 1 more.","effects":[{"type":"HEAL","amount":2},{"type":"CONDITIONAL","condition":"behind","effects":[{"type":"HEAL","amount":1}]}],"priority":40,"archetype":"Recovery","artIndex":5,"tags":["recovery","action","low-value"],"mechanicalVersion":6,"rarity":"common","affinityRequirements":{"anyOf":[{"affinity":"spirit"},{"affinity":"wild"}]},"set":"first-light","collectorNumber":48,"balanceMetadata":{"intent":"Recovery option; overlapping Affinity access","complexity":1,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 2–4"}'::jsonb,false),
('island-pull','card',6,'{"id":"island-pull","name":"Island Pull","category":"Attack","timing":"ACTION","requirement":{"count":1,"min":8},"text":"Deal 5 damage.","effects":[{"type":"DAMAGE","amount":5}],"priority":40,"archetype":"Attack","artIndex":5,"tags":["attack","action"],"mechanicalVersion":6,"rarity":"common","affinityRequirements":{"affinity":"might"},"set":"first-light","collectorNumber":49,"balanceMetadata":{"intent":"Attack option; overlapping Affinity access","complexity":1,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 8+"}'::jsonb,false),
('bold-wager','card',6,'{"id":"bold-wager","name":"Bold Wager","category":"Setup","timing":"ACTION","requirement":{"count":1,"any":true,"life":1},"text":"Spend 1 Life. Empower your next damage effect by 2. Expires at the end of your next turn.","effects":[{"type":"STATUS","status":"power","amount":2,"duration":1}],"priority":40,"archetype":"Setup","artIndex":5,"tags":["setup","action"],"mechanicalVersion":6,"rarity":"uncommon","affinityRequirements":{"anyOf":[{"affinity":"shadow"},{"affinity":"chaos"}]},"set":"first-light","collectorNumber":50,"balanceMetadata":{"intent":"Setup option; overlapping Affinity access","complexity":2,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Any Omen face · 1 Life"}'::jsonb,false),
('wavebreaker','card',6,'{"id":"wavebreaker","name":"Wavebreaker","category":"Attack","timing":"ACTION","requirement":{"count":1,"min":5,"max":6},"text":"Convert up to 3 Ward into damage, then deal 2 damage.","effects":[{"type":"CONVERT","from":"guard","amount":3,"effects":[{"type":"DAMAGE","amount":1}]},{"type":"DAMAGE","amount":2}],"priority":40,"archetype":"Attack","artIndex":5,"tags":["attack","action"],"mechanicalVersion":6,"rarity":"rare","affinityRequirements":{"anyOf":[{"allOf":[{"affinity":"might"},{"affinity":"spirit"}]},{"allOf":[{"affinity":"might"},{"affinity":"guile"}]}]},"set":"first-light","collectorNumber":51,"balanceMetadata":{"intent":"Attack option; overlapping Affinity access","complexity":3,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 5–6"}'::jsonb,false),
('against-the-current','card',6,'{"id":"against-the-current","name":"Against the Current","category":"Prediction","timing":"ACTION","requirement":{"count":1,"min":4},"text":"Deal 2 damage. If the enemy has Ward, deal 2 more.","effects":[{"type":"DAMAGE","amount":2},{"type":"CONDITIONAL","condition":"enemyGuarding","effects":[{"type":"DAMAGE","amount":2}]}],"priority":40,"archetype":"Prediction","artIndex":5,"tags":["prediction","action"],"mechanicalVersion":6,"rarity":"common","affinityRequirements":{"anyOf":[{"affinity":"guile"},{"affinity":"order"}]},"set":"first-light","collectorNumber":52,"balanceMetadata":{"intent":"Prediction option; overlapping Affinity access","complexity":1,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 4+"}'::jsonb,false),
('quick-strike','card',6,'{"id":"quick-strike","name":"Quick Strike","category":"Attack","timing":"ACTION","requirement":{"count":1,"min":1,"max":3},"text":"Deal 2 damage.","effects":[{"type":"DAMAGE","amount":2}],"priority":40,"archetype":"Attack","artIndex":0,"tags":["attack","action","low-value"],"mechanicalVersion":6,"rarity":"common","affinityRequirements":null,"set":"first-light","collectorNumber":53,"balanceMetadata":{"intent":"Attack option; universal access","complexity":1,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 1–3"}'::jsonb,true),
('web-turn','card',6,'{"id":"web-turn","name":"Web Turn","category":"Manipulation","timing":"REACTION","requirement":{"count":1,"min":6,"max":6},"text":"Redirect the declared enemy action back to its user.","effects":[{"type":"REDIRECT"}],"priority":20,"archetype":"Manipulation","artIndex":1,"tags":["manipulation","reaction"],"mechanicalVersion":6,"rarity":"common","affinityRequirements":{"anyOf":[{"affinity":"guile"},{"affinity":"wisdom"}]},"set":"first-light","collectorNumber":54,"balanceMetadata":{"intent":"Manipulation option; overlapping Affinity access","complexity":1,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value exactly 6"}'::jsonb,true),
('precision-cut','card',6,'{"id":"precision-cut","name":"Precision Cut","category":"Attack","timing":"ACTION","requirement":{"count":1,"min":5,"max":5},"text":"Deal 3 damage; ignore 1 Ward.","effects":[{"type":"DAMAGE","amount":3,"guardPierce":1}],"priority":40,"archetype":"Attack","artIndex":2,"tags":["attack","action"],"mechanicalVersion":6,"rarity":"common","affinityRequirements":{"allOf":[{"affinity":"might"},{"affinity":"wisdom"}]},"set":"first-light","collectorNumber":55,"balanceMetadata":{"intent":"Attack option; overlapping Affinity access","complexity":1,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value exactly 5"}'::jsonb,false),
('counterstrike','card',6,'{"id":"counterstrike","name":"Counterstrike","category":"Counter","timing":"REACTION","requirement":{"count":1,"min":8,"condition":"enemyAttacking"},"text":"If this attack damages your Life, deal 4 damage back.","effects":[{"type":"COUNTERSTRIKE","amount":4}],"priority":20,"archetype":"Counter","artIndex":0,"tags":["counter","reaction"],"mechanicalVersion":6,"rarity":"common","affinityRequirements":null,"set":"first-light","collectorNumber":56,"balanceMetadata":{"intent":"Counter option; universal access","complexity":1,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"Value 8+ · Against an attack"}'::jsonb,true),
('ritual','card',6,'{"id":"ritual","name":"Ritual","category":"Setup","timing":"ACTION","requirement":{"count":2,"exact":10,"min":10,"max":10},"text":"Heal 5 Life and gain 3 Ward.","effects":[{"type":"HEAL","amount":5},{"type":"GUARD","amount":3}],"priority":40,"archetype":"Setup","artIndex":4,"tags":["setup","action"],"mechanicalVersion":6,"rarity":"mythic","affinityRequirements":{"anyOf":[{"allOf":[{"affinity":"spirit"},{"affinity":"wisdom"}]},{"allOf":[{"affinity":"wild"},{"affinity":"chaos"}]}]},"set":"first-light","collectorNumber":57,"balanceMetadata":{"intent":"Setup option; overlapping Affinity access","complexity":4,"repeatability":"resource-limited","reviewNotes":"Prototype; measured per legal Legend and Omen profile, not rarity-scaled."},"persistence":"none","requirementLabel":"2 Values totaling exactly 10"}'::jsonb,false),
('meditate','card',6,'{"id":"meditate","name":"Meditate","affinityRequirements":null,"requirement":{"count":1,"min":2,"max":5},"text":"Gain 1 Focus.","effects":[{"type":"GAIN_CONTROL","amount":1}],"timing":"ACTION","rarity":"common","set":"first-light","collectorNumber":58,"category":"Setup","archetype":"Omen utility","priority":40,"artIndex":1,"tags":["omen","utility","action"],"mechanicalVersion":6,"balanceMetadata":{"intent":"Gain 1 Focus.","complexity":1,"repeatability":"resource-limited","reviewNotes":"Consumes an Omen; no free reusable activation."},"persistence":"none","requirementLabel":"Value 2–5"}'::jsonb,true),
('hollow-sign','card',6,'{"id":"hollow-sign","name":"Hollow Sign","affinityRequirements":{"anyOf":[{"affinity":"chaos"},{"affinity":"shadow"}]},"requirement":{"count":1,"void":true,"unused":1},"text":"Flip your first other available or Held Omen.","effects":[{"type":"FLIP_DIE","target":"self","omenTarget":"unspent"}],"timing":"ACTION","rarity":"rare","set":"first-light","collectorNumber":59,"category":"Manipulation","archetype":"Omen utility","priority":40,"artIndex":1,"tags":["omen","utility","action"],"mechanicalVersion":6,"balanceMetadata":{"intent":"Flip your first other available or Held Omen.","complexity":3,"repeatability":"resource-limited","reviewNotes":"Consumes an Omen; no free reusable activation."},"persistence":"none","requirementLabel":"Void · 1 other unused Omen"}'::jsonb,false),
('thread-the-path','card',6,'{"id":"thread-the-path","name":"Thread the Path","affinityRequirements":{"affinity":"wisdom"},"requirement":{"count":1,"exact":5,"min":5,"max":5},"text":"Shift the first Omen paying for the enemy Action down by 1. Recheck its requirement.","effects":[{"type":"SHIFT_DIE","target":"enemy","direction":-1}],"timing":"REACTION","rarity":"uncommon","set":"first-light","collectorNumber":60,"category":"Manipulation","archetype":"Omen utility","priority":20,"artIndex":1,"tags":["omen","utility","reaction"],"mechanicalVersion":6,"balanceMetadata":{"intent":"Shift the first Omen paying for the enemy Action down by 1. Recheck its requirement.","complexity":1,"repeatability":"resource-limited","reviewNotes":"Consumes an Omen; no free reusable activation."},"persistence":"none","requirementLabel":"Value exactly 5"}'::jsonb,false),
('standard-d4','die',6,'{"id":"standard-d4","name":"Silent Step","size":4,"faceCount":4,"faces":[{"type":"number","value":1,"displayIcon":"1","balanceWeight":0.5},{"type":"number","value":2,"displayIcon":"2","balanceWeight":1},{"type":"number","value":3,"displayIcon":"3","balanceWeight":1.5},{"type":"number","value":4,"displayIcon":"4","balanceWeight":2}],"opposites":[3,2,1,0],"tags":["standard"],"compatibleLegendTags":["all"],"rarity":"common","mechanicalVersion":6,"description":"Fixed Values. A clear probability profile for precise Loadout choices."}'::jsonb,true),
('standard-d6','die',6,'{"id":"standard-d6","name":"Iron Path","size":6,"faceCount":6,"faces":[{"type":"number","value":1,"displayIcon":"1","balanceWeight":0.5},{"type":"number","value":2,"displayIcon":"2","balanceWeight":1},{"type":"number","value":3,"displayIcon":"3","balanceWeight":1.5},{"type":"number","value":4,"displayIcon":"4","balanceWeight":2},{"type":"number","value":5,"displayIcon":"5","balanceWeight":2.5},{"type":"number","value":6,"displayIcon":"6","balanceWeight":3}],"opposites":[5,4,3,2,1,0],"tags":["standard"],"compatibleLegendTags":["all"],"rarity":"common","mechanicalVersion":6,"description":"Fixed Values. A clear probability profile for precise Loadout choices."}'::jsonb,true),
('standard-d8','die',6,'{"id":"standard-d8","name":"Mountain Wind","size":8,"faceCount":8,"faces":[{"type":"number","value":1,"displayIcon":"1","balanceWeight":0.5},{"type":"number","value":2,"displayIcon":"2","balanceWeight":1},{"type":"number","value":3,"displayIcon":"3","balanceWeight":1.5},{"type":"number","value":4,"displayIcon":"4","balanceWeight":2},{"type":"number","value":5,"displayIcon":"5","balanceWeight":2.5},{"type":"number","value":6,"displayIcon":"6","balanceWeight":3},{"type":"number","value":7,"displayIcon":"7","balanceWeight":3.5},{"type":"number","value":8,"displayIcon":"8","balanceWeight":4}],"opposites":[7,6,5,4,3,2,1,0],"tags":["standard"],"compatibleLegendTags":["all"],"rarity":"common","mechanicalVersion":6,"description":"Fixed Values. A clear probability profile for precise Loadout choices."}'::jsonb,true),
('standard-d10','die',6,'{"id":"standard-d10","name":"Sun Coil","size":10,"faceCount":10,"faces":[{"type":"number","value":1,"displayIcon":"1","balanceWeight":0.5},{"type":"number","value":2,"displayIcon":"2","balanceWeight":1},{"type":"number","value":3,"displayIcon":"3","balanceWeight":1.5},{"type":"number","value":4,"displayIcon":"4","balanceWeight":2},{"type":"number","value":5,"displayIcon":"5","balanceWeight":2.5},{"type":"number","value":6,"displayIcon":"6","balanceWeight":3},{"type":"number","value":7,"displayIcon":"7","balanceWeight":3.5},{"type":"number","value":8,"displayIcon":"8","balanceWeight":4},{"type":"number","value":9,"displayIcon":"9","balanceWeight":4.5},{"type":"number","value":10,"displayIcon":"10","balanceWeight":5}],"opposites":[9,8,7,6,5,4,3,2,1,0],"tags":["standard"],"compatibleLegendTags":["all"],"rarity":"common","mechanicalVersion":6,"description":"Fixed Values. A clear probability profile for precise Loadout choices."}'::jsonb,false),
('standard-d12','die',6,'{"id":"standard-d12","name":"Old Root","size":12,"faceCount":12,"faces":[{"type":"number","value":1,"displayIcon":"1","balanceWeight":0.5},{"type":"number","value":2,"displayIcon":"2","balanceWeight":1},{"type":"number","value":3,"displayIcon":"3","balanceWeight":1.5},{"type":"number","value":4,"displayIcon":"4","balanceWeight":2},{"type":"number","value":5,"displayIcon":"5","balanceWeight":2.5},{"type":"number","value":6,"displayIcon":"6","balanceWeight":3},{"type":"number","value":7,"displayIcon":"7","balanceWeight":3.5},{"type":"number","value":8,"displayIcon":"8","balanceWeight":4},{"type":"number","value":9,"displayIcon":"9","balanceWeight":4.5},{"type":"number","value":10,"displayIcon":"10","balanceWeight":5},{"type":"number","value":11,"displayIcon":"11","balanceWeight":5.5},{"type":"number","value":12,"displayIcon":"12","balanceWeight":6}],"opposites":[11,10,9,8,7,6,5,4,3,2,1,0],"tags":["standard"],"compatibleLegendTags":["all"],"rarity":"common","mechanicalVersion":6,"description":"Fixed Values. A clear probability profile for precise Loadout choices."}'::jsonb,true),
('standard-d20','die',6,'{"id":"standard-d20","name":"Star Pilgrim","size":20,"faceCount":20,"faces":[{"type":"number","value":1,"displayIcon":"1","balanceWeight":0.5},{"type":"number","value":2,"displayIcon":"2","balanceWeight":1},{"type":"number","value":3,"displayIcon":"3","balanceWeight":1.5},{"type":"number","value":4,"displayIcon":"4","balanceWeight":2},{"type":"number","value":5,"displayIcon":"5","balanceWeight":2.5},{"type":"number","value":6,"displayIcon":"6","balanceWeight":3},{"type":"number","value":7,"displayIcon":"7","balanceWeight":3.5},{"type":"number","value":8,"displayIcon":"8","balanceWeight":4},{"type":"number","value":9,"displayIcon":"9","balanceWeight":4.5},{"type":"number","value":10,"displayIcon":"10","balanceWeight":5},{"type":"number","value":11,"displayIcon":"11","balanceWeight":5.5},{"type":"number","value":12,"displayIcon":"12","balanceWeight":6},{"type":"number","value":13,"displayIcon":"13","balanceWeight":6.5},{"type":"number","value":14,"displayIcon":"14","balanceWeight":7},{"type":"number","value":15,"displayIcon":"15","balanceWeight":7.5},{"type":"number","value":16,"displayIcon":"16","balanceWeight":8},{"type":"number","value":17,"displayIcon":"17","balanceWeight":8.5},{"type":"number","value":18,"displayIcon":"18","balanceWeight":9},{"type":"number","value":19,"displayIcon":"19","balanceWeight":9.5},{"type":"number","value":20,"displayIcon":"20","balanceWeight":10}],"opposites":[19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0],"tags":["standard"],"compatibleLegendTags":["all"],"rarity":"common","mechanicalVersion":6,"description":"Fixed Values. A clear probability profile for precise Loadout choices."}'::jsonb,false),
('guardian-d6','die',6,'{"id":"guardian-d6","name":"Warden’s Oath","size":6,"faceCount":6,"faces":[{"type":"blank","value":0,"displayIcon":"○","balanceWeight":0},{"type":"number","value":2,"displayIcon":"2","balanceWeight":1},{"type":"number","value":3,"displayIcon":"3","balanceWeight":1.5},{"type":"number","value":4,"displayIcon":"4","balanceWeight":2},{"type":"blank","value":0,"displayIcon":"○","balanceWeight":0},{"type":"symbol","value":0,"effectId":"guard","displayIcon":"◇","balanceWeight":3,"guardValue":3,"tags":["Ward"]}],"opposites":[5,4,3,2,1,0],"tags":["signature","Ward","Defense"],"compatibleLegendTags":["all"],"rarity":"rare","mechanicalVersion":6,"description":"Two Voids and a Ward Sigil replace three Values. A compact defensive Omen."}'::jsonb,true),
('trickster-d8','die',6,'{"id":"trickster-d8","name":"Spider’s Gambit","size":8,"faceCount":8,"faces":[{"type":"number","value":1,"displayIcon":"1","balanceWeight":0.5},{"type":"number","value":2,"displayIcon":"2","balanceWeight":1},{"type":"blank","value":0,"displayIcon":"○","balanceWeight":0},{"type":"number","value":4,"displayIcon":"4","balanceWeight":2},{"type":"number","value":5,"displayIcon":"5","balanceWeight":2.5},{"type":"symbol","value":0,"effectId":"swap","displayIcon":"⇄","balanceWeight":3,"tags":["Shift Sigil"]},{"type":"blank","value":0,"displayIcon":"○","balanceWeight":0},{"type":"number","value":8,"displayIcon":"8","balanceWeight":4}],"opposites":[7,6,5,4,3,2,1,0],"tags":["signature","Guile","Redirect"],"compatibleLegendTags":["all"],"rarity":"rare","mechanicalVersion":6,"description":"Two Voids and a Shift Sigil trade numerical coverage for a held redirect opportunity."}'::jsonb,true),
('tengu-d6-0','die',6,'{"id":"tengu-d6-0","name":"Mountain Precision","size":6,"faceCount":6,"faces":[{"type":"number","value":1,"displayIcon":"1","balanceWeight":0.5},{"type":"number","value":2,"displayIcon":"2","balanceWeight":1},{"type":"number","value":3,"displayIcon":"3","balanceWeight":1.5},{"type":"number","value":5,"displayIcon":"5","balanceWeight":2.5},{"type":"number","value":5,"displayIcon":"5","balanceWeight":2.5},{"type":"symbol","value":0,"effectId":"redirect","displayIcon":"↪","balanceWeight":3,"tags":["Redirect Sigil"]}],"opposites":[5,4,3,2,1,0],"tags":["signature","Precision","Reaction"],"compatibleLegendTags":["all"],"rarity":"rare","mechanicalVersion":6,"description":"Two faces show 5. A Redirect Sigil replaces 6; Value 4 is absent. Precision with a clear tradeoff."}'::jsonb,false),
('leshy-d8-0','die',6,'{"id":"leshy-d8-0","name":"Shifting Bark","size":8,"faceCount":8,"faces":[{"type":"blank","value":0,"displayIcon":"○","balanceWeight":0},{"type":"number","value":2,"displayIcon":"2","balanceWeight":1},{"type":"number","value":3,"displayIcon":"3","balanceWeight":1.5},{"type":"number","value":4,"displayIcon":"4","balanceWeight":2},{"type":"number","value":5,"displayIcon":"5","balanceWeight":2.5},{"type":"number","value":6,"displayIcon":"6","balanceWeight":3},{"type":"blank","value":0,"displayIcon":"○","balanceWeight":0},{"type":"number","value":8,"displayIcon":"8","balanceWeight":4}],"opposites":[7,6,5,4,3,2,1,0],"tags":["signature","Void","Adaptation"],"compatibleLegendTags":["all"],"rarity":"rare","mechanicalVersion":6,"description":"Voids replace 1 and 7. Pairs with Void conversion and flexible low or middle Values."}'::jsonb,false),
('quetzalcoatl-d10-0','die',6,'{"id":"quetzalcoatl-d10-0","name":"Dawn Coil","size":10,"faceCount":10,"faces":[{"type":"blank","value":0,"displayIcon":"○","balanceWeight":0},{"type":"number","value":2,"displayIcon":"2","balanceWeight":1},{"type":"number","value":3,"displayIcon":"3","balanceWeight":1.5},{"type":"number","value":4,"displayIcon":"4","balanceWeight":2},{"type":"number","value":5,"displayIcon":"5","balanceWeight":2.5},{"type":"number","value":6,"displayIcon":"6","balanceWeight":3},{"type":"number","value":7,"displayIcon":"7","balanceWeight":3.5},{"type":"number","value":8,"displayIcon":"8","balanceWeight":4},{"type":"blank","value":0,"displayIcon":"○","balanceWeight":0},{"type":"symbol","value":0,"effectId":"guard","displayIcon":"◇","balanceWeight":3,"guardValue":3,"tags":["Ward"]}],"opposites":[9,8,7,6,5,4,3,2,1,0],"tags":["signature","Ward","Restoration"],"compatibleLegendTags":["all"],"rarity":"rare","mechanicalVersion":6,"description":"Two Voids and a Ward Sigil replace 1, 9 and 10. Middle Values support restoration and setup."}'::jsonb,false),
('maui-d10-0','die',6,'{"id":"maui-d10-0","name":"Voyager’s Knot","size":10,"faceCount":10,"faces":[{"type":"number","value":1,"displayIcon":"1","balanceWeight":0.5},{"type":"number","value":2,"displayIcon":"2","balanceWeight":1},{"type":"number","value":3,"displayIcon":"3","balanceWeight":1.5},{"type":"number","value":4,"displayIcon":"4","balanceWeight":2},{"type":"number","value":5,"displayIcon":"5","balanceWeight":2.5},{"type":"number","value":6,"displayIcon":"6","balanceWeight":3},{"type":"number","value":7,"displayIcon":"7","balanceWeight":3.5},{"type":"number","value":8,"displayIcon":"8","balanceWeight":4},{"type":"number","value":4,"displayIcon":"4","balanceWeight":2},{"type":"number","value":5,"displayIcon":"5","balanceWeight":2.5}],"opposites":[9,8,7,6,5,4,3,2,1,0],"tags":["signature","MidValue","Tempo"],"compatibleLegendTags":["all"],"rarity":"rare","mechanicalVersion":6,"description":"Values 4 and 5 each appear twice, replacing 9 and 10. Reliable middle Values; no Sigils or Voids."}'::jsonb,false)
on conflict(id) do update set definition=excluded.definition,version=excluded.version,starter=excluded.starter,enabled=true;
insert into public.inventory(user_id,content_id) select u.id,c.id from auth.users u cross join public.content_catalog c where c.starter and c.enabled on conflict do nothing;

create temporary table legacy_card_ids(old_id text primary key,new_id text not null) on commit drop;
insert into legacy_card_ids values ('basajaun-crush','crush'),('basajaun-ancient-root','root-ward'),('basajaun-barkskin','barkskin'),('basajaun-herensuge','herensuge'),('basajaun-deep-roots','deep-roots'),('basajaun-oakheart','oakheart'),('basajaun-thorn-return','thorn-return'),('basajaun-fell-the-axe','fell-the-axe'),('basajaun-sanctuary','sanctuary'),('basajaun-mountain-weight','crush'),('basajaun-quiet-grove','deep-roots'),('basajaun-last-stand','wolf-shape'),('anansi-silken-cut','silken-cut'),('anansi-web-shelter','root-ward'),('anansi-read-the-thread','read-the-thread'),('anansi-web-shift','web-shift'),('anansi-false-promise','false-promise'),('anansi-unravel','unravel'),('anansi-borrowed-time','borrowed-time'),('anansi-spider-s-patience','spider-s-patience'),('anansi-tangled-path','web-shift'),('anansi-story-s-end','story-s-end'),('anansi-needle-truth','crush'),('anansi-hidden-meaning','hidden-meaning'),('tengu-gale-cut','gale-cut'),('tengu-feather-guard','root-ward'),('tengu-perfect-riposte','perfect-riposte'),('tengu-sky-sever','sky-sever'),('tengu-first-wind','first-wind'),('tengu-still-mind','still-mind'),('tengu-raven-wing','raven-wing'),('tengu-peak-strike','peak-strike'),('tengu-windstep','windstep'),('tengu-watchful-blade','watchful-blade'),('tengu-mountain-silence','mountain-silence'),('tengu-falling-leaf','falling-leaf'),('leshy-branch-lash','branch-lash'),('leshy-moss-mantle','moss-mantle'),('leshy-wolf-shape','wolf-shape'),('leshy-lost-path','lost-path'),('leshy-new-skin','new-skin'),('leshy-elk-shape','mountain-silence'),('leshy-bramble-trap','bramble-trap'),('leshy-forest-echo','windstep'),('leshy-deepwood','ritual'),('leshy-wild-bloom','wild-bloom'),('leshy-crooked-bough','crooked-bough'),('leshy-night-spores','night-spores'),('quetzalcoatl-sun-lance','sun-lance'),('quetzalcoatl-feather-aegis','root-ward'),('quetzalcoatl-first-light','first-light'),('quetzalcoatl-solar-ascent','herensuge'),('quetzalcoatl-jade-breath','deep-roots'),('quetzalcoatl-skyfire','island-pull'),('quetzalcoatl-offering','offering'),('quetzalcoatl-dawn-shield','dawn-shield'),('quetzalcoatl-radiant-coil','burning-crown'),('quetzalcoatl-open-sky','open-sky'),('quetzalcoatl-burning-crown','burning-crown'),('quetzalcoatl-horizon','horizon'),('maui-hook-strike','silken-cut'),('maui-ocean-shelter','root-ward'),('maui-daring-feint','daring-feint'),('maui-snare-the-sun','herensuge'),('maui-turnabout','turnabout'),('maui-rising-tide','rising-tide'),('maui-stolen-tempo','raven-wing'),('maui-island-pull','island-pull'),('maui-rope-trick','web-shift'),('maui-bold-wager','bold-wager'),('maui-wavebreaker','wavebreaker'),('maui-against-the-current','against-the-current'),('basajaun-quick-strike','quick-strike'),('anansi-web-turn','web-turn'),('tengu-precision-cut','precision-cut'),('basajaun-counterstrike','counterstrike'),('quetzalcoatl-ritual','ritual');
insert into public.inventory(user_id,content_id,source) select i.user_id,m.new_id,'shared-pool-migration' from public.inventory i join legacy_card_ids m on m.old_id=i.content_id on conflict do nothing;
-- Do not grant the whole new set; preserve only old entitlements plus the starter collection.
update public.content_catalog set enabled=false,starter=false where id in(select old_id from legacy_card_ids);
create or replace function public.meets_affinity(affinities jsonb,requirements jsonb)
returns boolean language plpgsql immutable security invoker set search_path='' as $$
declare child jsonb;
begin
 if requirements is null or requirements='null'::jsonb then return true; end if;
 if requirements ? 'affinity' then return coalesce(affinities ? (requirements->>'affinity'),false); end if;
 if requirements ? 'allOf' then
  if jsonb_array_length(requirements->'allOf')=0 then return false; end if;
  for child in select value from jsonb_array_elements(requirements->'allOf') loop
   if not public.meets_affinity(affinities,child) then return false; end if;
  end loop; return true;
 end if;
 if requirements ? 'anyOf' then
  for child in select value from jsonb_array_elements(requirements->'anyOf') loop
   if public.meets_affinity(affinities,child) then return true; end if;
  end loop;
 end if;
 return false;
end $$;
revoke all on function public.meets_affinity(jsonb,jsonb) from public,anon;
grant execute on function public.meets_affinity(jsonb,jsonb) to authenticated,service_role;
create temporary table migration_starter_kits(legend_id text primary key,dice text[]) on commit drop;
insert into migration_starter_kits values ('basajaun',array['standard-d12','standard-d8','guardian-d6']),('anansi',array['trickster-d8','standard-d6','standard-d4']),('tengu',array['tengu-d6-0','standard-d8','standard-d6']),('leshy',array['leshy-d8-0','standard-d8','standard-d6']),('quetzalcoatl',array['quetzalcoatl-d10-0','standard-d8','standard-d6']),('maui',array['maui-d10-0','standard-d8','standard-d6']);
insert into public.inventory(user_id,content_id,source) select i.user_id,piece,'omen-catalog-migration' from public.inventory i join migration_starter_kits k on k.legend_id=i.content_id cross join lateral unnest(k.dice) piece on conflict do nothing;

-- Retain legal migrated slots, then fill from owned legal Cards in collector order.
update public.loadouts l set die_ids=case when exists(select 1 from unnest(l.die_ids) d left join public.content_catalog c on c.id=d where c.id is null or not c.enabled) then (select dice from migration_starter_kits where legend_id=l.legend_id) else l.die_ids end, card_ids=array(
 select candidate.id from (
 select distinct on(c.id) c.id,coalesce(old.ordinality,1000) slot,(c.definition->>'collectorNumber')::int number
 from public.inventory i join public.content_catalog c on c.id=i.content_id
 join public.content_catalog legend on legend.id=l.legend_id
 left join lateral (select o.ordinality from unnest(l.card_ids) with ordinality o(id,ordinality) left join legacy_card_ids m on m.old_id=o.id where coalesce(m.new_id,o.id)=c.id order by o.ordinality limit 1) old on true
 where i.user_id=l.user_id and c.kind='card' and c.enabled and public.meets_affinity(legend.definition->'affinities',c.definition->'affinityRequirements')
 ) candidate order by candidate.slot,candidate.number limit 4
);
create or replace function public.validate_saved_loadout() returns trigger language plpgsql security invoker set search_path='' as $$
declare piece text; affinities jsonb; requirements jsonb;
begin
  if (select count(distinct c) from unnest(new.card_ids) c) <> 4 then raise exception 'Choose four distinct cards'; end if;
  if not exists(select 1 from public.content_catalog where id=new.legend_id and kind='legend' and enabled) then raise exception 'Invalid Legend'; end if;
  select definition->'affinities' into affinities from public.content_catalog where id=new.legend_id;
  foreach piece in array new.card_ids loop
    if not exists(select 1 from public.content_catalog where id=piece and kind='card' and enabled) then raise exception 'Invalid card'; end if;
    select definition->'affinityRequirements' into requirements from public.content_catalog where id=piece;
    if not public.meets_affinity(affinities,requirements) then raise exception 'Card % is incompatible with Legend Affinities',piece; end if;
  end loop;
  foreach piece in array new.die_ids loop
    if not exists(select 1 from public.content_catalog where id=piece and kind='die' and enabled) then raise exception 'Invalid die'; end if;
  end loop;
  foreach piece in array array[new.legend_id] || new.card_ids || new.die_ids loop
    if not exists(select 1 from public.inventory where user_id=new.user_id and content_id=piece) then raise exception 'Content is not owned'; end if;
  end loop;
  new.updated_at=now(); return new;
end $$;

